### ISSUE TITLE
content missing / weird redirects

### ISSUE THREAD

**Issue by Likqez** [i-voted-for-biden2/howoldisjava8.today#189]
I noticed a strange behaviour when changing the language in the url bar.

I default get redirected to ``/de`` but if i change the uri to``/en`` no text is rendered.
Only the background gets displayed.

If i change the language to ``/es``instead, i get redirected to ``/de`` again.
The loading text is still getting shown, but then dissapears showing only the background or redirecting me.

**Comment by DRSchlaubi** [comment]
>  default get redirected to /de but if i change the uri to/en no text is rendered.
Only the background gets displayed.

That's because `/en` doesn't exist the english version is on just the root domain

> If i change the language to /esinstead, i get redirected to /de again.

Your GH profile tells me you're from Germany so you probably have your browser set to german, so the site will always redirect you to /de no matter what url you were on before. I experimented with it and it either had no browser based redirect or this behavior

If you change your browser language to english you will always be redirect to `/`
